config/routes.rb
#map.namespace :admin do |admin|
#  admin.resources :comments
#  admin.resources :comment_types
#
#  admin.resources :orders, :member => {:comments => :get} do |order|
#    order.resources :shipments, :member => {:comments => :get}
#  end
#end
#

Spree::Core::Engine.routes.prepend do
  namespace :admin do
    resources :comments
    resources :comment_types

    resources :orders do
      member do
        get :comments
      end

      resources :shipments do
        member do
         get :comments
       end
      end
    end
  end

#match '/admin/comments' => 'admin/comments', :via => [:get, :post]
#  match '/admin/comment_types' => 'admin/comment_types', :via => [:get, :post]
end

app/models/spree/comment.rb
class Spree::Comment < ActiveRecord::Base
  include ActsAsCommentable::Comment

  belongs_to :commentable, :polymorphic => true
  belongs_to :comment_type

  default_scope :order => 'created_at ASC'

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable

  # NOTE: Comments belong to a user
  belongs_to :user

  attr_accessible :commentable_id, :commentable_type, :user_id, :comment_type_id, :comment

end

app/models/spree/comment_type.rb
class Spree::CommentType < ActiveRecord::Base
  has_many :comments
  attr_accessible :name, :applies_to
end

app/models/spree/order_decorator.rb
Spree::Order.class_eval do
  acts_as_commentable
end

app/models/spree/shipment_decorator.rb
Spree::Shipment.class_eval do
  acts_as_commentable
end

app/controllers/spree/admin/comment_types_controller.rb
class Spree::Admin::CommentTypesController < Spree::Admin::ResourceController
end

app/controllers/spree/admin/comments_controller.rb
class Spree::Admin::CommentsController < Spree::Admin::ResourceController
  private
  
  def location_after_save
    :back
  end
end

app/controllers/spree/admin/orders_controller_decorator.rb
Spree::Admin::OrdersController.class_eval do
  def comments
    load_order
    @comment_types = Spree::CommentType.where(:applies_to => "Order")
  end
end

app/controllers/spree/admin/shipments_controller_decorator.rb
Spree::Api::ShipmentsController.class_eval do
  def comments
    shipment
    @comment_types = Spree::CommentType.where(:applies_to => "Shipment")
  end
end

app/views/spree/admin/comment_types/_form.html.erb
<div id="admin_comment_type_form_fields" data-hook>
  <%= f.field_container :name do %>
    <%= f.label :name, Spree.t(:name) %><br />
    <%= f.text_field :name, :class => 'fullwidth title' %>
    <%= error_message_on :comment_type, :name %>
  <% end %>

  <%= f.field_container :applies_to do %>
    <%= f.label :applies_to, Spree.t(:applies_to) %><br />
    <%= f.text_field :applies_to, :value => f.object.nil? ? 'Order' : f.object.applies_to, :class => 'fullwidth title' %>
    <%= error_message_on :comment_type, :applies_to%>
  <% end %>

</div>

app/views/spree/admin/comment_types/edit.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<div id="admin_comment_type_edit_form_header" data-hook>
  <h1><%= Spree.t(:editing_comment_type) %></h1>
  <%= render 'spree/shared/error_messages', :target => @comment_type %>
</div>

<div id="admin_comment_type_edit_form" data-hook>
  <%= form_for(@comment_type, :url => object_url, :html => { :method => :put }) do |f| %>
    <%= render :partial => 'form', :locals => { :f => f } %>

    <div id="admin_comment_type_edit_form_buttons" data-hook>
      <%= render :partial => 'spree/admin/shared/edit_resource_links' %>
    </div>
  <% end %>
</div>

app/views/spree/admin/comment_types/index.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<% content_for :page_title do %>
  <%= Spree.t(:comment_types) %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to Spree.t(:new_comment_type), new_object_url, :icon => 'icon-plus', :id => 'admin_new_comment_type_link' %>
  </li>
<% end %>

<table class="index" id='listing_comment_types'>
  <colgroup>
    <col style="width: 40%">
    <col style="width: 45%">
    <col style="width: 15%">
  </colgroup>
  <thead>
    <tr data-hook="admin_comment_types_index_headers">
      <th><%= Spree.t(:name) %></th>
      <th><%= Spree.t(:applies_to) %></th>
      <th data-hook="admin_comment_types_index_header_actions" class="actions"></th>
    </tr>
  </thead>
  <tbody>
    <% @comment_types.each do |comment_type| %>
      <tr id="<%= dom_id comment_type %>">
      <tr id="<%= spree_dom_id comment_type %>" data-hook="admin_comment_types_index_rows" class="<%= cycle('odd', 'even')%>">
        <td><%= comment_type.name %></td>
        <td><%= comment_type.applies_to %></td>
        <td data-hook="admin_comment_types_index_row_actions" class="actions">
          <%= link_to_edit comment_type, :no_text => true %>
          <%= link_to_delete comment_type, :no_text => true  %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/spree/admin/comment_types/new.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<% content_for :page_title do %>
  <%= Spree.t(:new_comment_type) %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to Spree.t(:back_to_comment_types_list), admin_comment_types_path, :icon => 'icon-arrow-left' %>
  </li>
<% end %>

<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @comment_type } %>

<%= form_for(:comment_type, :url => collection_url) do |f| %>
  <fieldset class="no-border-top">
    <%= render :partial => 'form', :locals => { :f => f } %>
    <div data-hook="buttons" class="filter-actions actions">
      <%= button Spree.t(:create), 'icon-ok' %>
    </div>
  </fieldset>
<% end %>

app/views/spree/admin/orders/_tab.html.erb
<li <%== ' class="active"' if (defined? current and current == 'Comments') %>>
  <%= link_to Spree.t(:comments), comments_admin_order_url(@order) %>
</li>

app/views/spree/admin/orders/comments.html.erb
<%= render 'spree/admin/shared/order_tabs', :current => 'Comments' %>
<%= render 'spree/admin/shared/comments', :commentable => @order %>

app/views/spree/admin/shared/_comment_list.html.erb
<table class="index">
  <colgroup>
    <col style="width: 18%" />
    <col style="width: 15%" />
    <col style="width: 20%" />
    <col style="width: 47%" />
  </colgroup>
  <thead>
    <tr>
      <th><%= "#{t('spree.date')}/#{t('spree.time')}" %></th>
      <th><%= Spree.t(:type) %></th>
      <th><%= Spree.t(:commenter) %></th>
      <th><%= Spree.t(:comment) %></th>
    </tr>
  </thead>
  <tbody>
    <% commentable.comments.reverse.each_with_index do |comment, index| %>
      <tr class="<%= cycle('odd', 'even')%>">
        <td class='align-center'><%= pretty_time(comment.created_at) %></td>
        <td class='align-center'><%= comment.comment_type.try(:name) || 'None' %></td>
        <td class='align-center'><%= comment.user.email %></td>
        <td><%= comment.comment.html_safe %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/spree/admin/shared/_comments.html.erb
<%= render 'spree/admin/shared/comment_list', :commentable => commentable %>

<div class="order-add-comment">
  <%= form_for(:comment, :url => admin_comments_url) do |f| %>
    <%= hidden_field_tag 'comment[commentable_id]', commentable.id %>
    <%= hidden_field_tag 'comment[commentable_type]', commentable.class %>
    <%= hidden_field_tag 'comment[user_id]', spree_current_user.id %>

    <fieldset data-hook="admin_comment_form_fields" class="no-border-top">
      <fieldset class="index no-border-bottom">
        <legend align="center"><%= Spree.t(:add_comment) %></legend>

        <div data-hook="comment_fields" class="row">
          <div class="alpha twelve columns">
            <% if @comment_types.present? %>
              <div class="field">
                <%= f.label :comment_type_id, Spree.t(:type) %>
                <%= f.select :comment_type_id, @comment_types.map{|ct| [ct.name, ct.id]},{} ,:class => 'fullwidth' %>
              </div>
            <% end %>
            <div class="field">
              <%= f.label :comment, Spree.t(:comment) %>
              <%= f.text_area :comment, :style => 'height:150px;', :class => 'fullwidth' %>
            </div>
          </div>
        </div>
      </fieldset>

      <div class="clear"></div>

      <div class="form-buttons filter-actions actions" data-hook="buttons">
        <%= button Spree.t(:add_comment), 'icon-arrow-right' %>
      </div>
    </fieldset>
  <% end %>
</div>

app/views/spree/admin/shipments/_button.html.erb
<li>
  <%= button_link_to Spree.t(:comments), comments_admin_order_shipment_url(@order, @shipment) %>
</li>

app/views/spree/admin/shipments/comments.html.erb
<%= render 'spree/admin/shared/order_tabs', :current => 'Shipments' %>

<% content_for :page_title do %>
  <i class="icon-arrow-right"></i> <%= Spree.t(:shipments) %> <i class="icon-arrow-right"></i> #<%= @shipment.number%> (<%= Spree.t(@shipment.state.to_sym, :scope => :state_names, :default => @shipment.state.to_s.humanize) %>)
<% end %>

<%= render 'spree/admin/shared/comments', {:commentable => @shipment, :comments_for => "Shipment ##{@shipment.number}"} %>